#!/bin/bash
set -e
set -o pipefail

# add group
if ! getent group | grep -q "^ravencore:" ; then
    echo "Creating system group: ravencore"
    groupadd --system ravencore
fi

# add user
if ! getent passwd | grep -q "^ravencore:"; then
    echo "Creating ravencore system user"
    useradd --gid "ravencore" --system -m ravencore
fi

# build nodejs addons
cd "/usr/opt/ravencore"
SKIP_BITCOIN_DOWNLOAD=1 npm rebuild

# setup data directory
mkdir -p "/home/ravencore/.ravencore/data"
chown -R ravencore:ravencore "/home/ravencore/.ravencore"

# start ravencore
if hash service 2> /dev/null; then
    service ravencore start || echo "ravencore could not be registered or started"
elif hash start 2> /dev/null; then
    start ravencore || echo "ravencore could not be registered or started"
elif hash systemctl 2> /dev/null; then
    {
        systemctl enable "ravencore.service" && \
            systemctl start "ravencore.service"
    } || echo "ravencore could not be registered or started"
else
    echo 'Your system does not appear to use upstart or systemd, so ravencore could not be started'
fi
