#!/bin/bash

set -e
set -o pipefail

if hash service 2> /dev/null; then
    service ravencore stop || echo "ravencore wasn't running!"
elif hash stop 2> /dev/null; then
    stop "$service_name" || echo "ravencore wasn't running!"
elif hash systemctl 2> /dev/null; then
    systemctl disable "ravencore.service" || echo "ravencore wasn't running!"
else
    echo "Your system does not appear to use upstart or systemd, so ravencore could not be stopped"
fi
